Repository UMC5th-DrinkingGourmet/dg-BackEnd, pull requests merged in 2024-09, with the labels that each got.

#250 Docs: 스웨거 설명 추가, Chore: 레시피북 이미지 조회 및 삭제 API 제거
  src/main/java/com/example/dgbackend/domain/combinationlike/controller/CombinationLikeController.java
  src/main/java/com/example/dgbackend/domain/recipeimage/controller/RecipeImageController.java
  src/main/java/com/example/dgbackend/domain/recipeimage/service/RecipeImageService.java
  src/main/java/com/example/dgbackend/domain/report/controller/ReportController.java
Labels: :memo: Docs, :construction_worker: Chore

#253 Feat: CombinationResult에 recommend 필드 추가
  src/main/java/com/example/dgbackend/domain/combination/dto/CombinationResponse.java
Labels: :sparkles: Feature

#254 [Main Merge] 스웨거 수정 및 recommend 추가
  src/main/java/com/example/dgbackend/domain/combination/dto/CombinationResponse.java
  src/main/java/com/example/dgbackend/domain/combinationlike/controller/CombinationLikeController.java
  src/main/java/com/example/dgbackend/domain/recipeimage/controller/RecipeImageController.java
  src/main/java/com/example/dgbackend/domain/recipeimage/service/RecipeImageService.java
  src/main/java/com/example/dgbackend/domain/report/controller/ReportController.java
Labels: Main Merge

#255 Fix: 충돌 오류 해결
  src/main/java/com/example/dgbackend/domain/recipeimage/controller/RecipeImageController.java
  src/main/java/com/example/dgbackend/domain/recipeimage/service/RecipeImageService.java
Labels: Fix

#260 [FEAT] 추천 이미지 캐싱 구현
  src/main/java/com/example/dgbackend/domain/cachedRecommendImage/CachedRecommendImage.java
  src/main/java/com/example/dgbackend/domain/cachedRecommendImage/repository/CachedRecommendImageRepository.java
  src/main/java/com/example/dgbackend/domain/cachedRecommendImage/service/CachedRecommendImageCommandService.java
  src/main/java/com/example/dgbackend/domain/cachedRecommendImage/service/CachedRecommendImageCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/cachedRecommendImage/service/CachedRecommendImageQueryService.java
  src/main/java/com/example/dgbackend/domain/cachedRecommendImage/service/CachedRecommendImageQueryServiceImpl.java
  src/main/java/com/example/dgbackend/domain/cachedRecommendImage/service/CachedRecommendImageScheduler.java
  src/main/java/com/example/dgbackend/domain/recommend/repository/RecommendRepository.java
  src/main/java/com/example/dgbackend/domain/recommend/service/RecommendCommandServiceImpl.java
Labels: :sparkles: Feature

#259 [Fix] 닉네임 중복 검사 로직 추가
  src/main/java/com/example/dgbackend/domain/member/service/MemberCommandServiceImpl.java
Labels: Fix

#263 [FEAT] 추천 정보 get API 구현
  src/main/java/com/example/dgbackend/domain/member/controller/MemberRestController.java
  src/main/java/com/example/dgbackend/domain/member/service/MemberQueryService.java
  src/main/java/com/example/dgbackend/domain/member/service/MemberQueryServiceImpl.java
Labels: :sparkles: Feature

#265 [FIX] 닉네임 중복 검사 로직 변경 & 만료시간 추가
  src/main/java/com/example/dgbackend/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/example/dgbackend/global/jwt/JwtProvider.java
Labels: Fix

#266 [Main Merge] 닉네임 중복검사, 유효성 추가, 추천 정보 조회 구현
  src/main/java/com/example/dgbackend/domain/member/controller/MemberRestController.java
  src/main/java/com/example/dgbackend/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/member/service/MemberQueryService.java
  src/main/java/com/example/dgbackend/domain/member/service/MemberQueryServiceImpl.java
  src/main/java/com/example/dgbackend/global/jwt/JwtProvider.java
Labels: Main Merge

#268 Feat: 로그 기능 구현
  .gitignore
  build.gradle
  src/main/java/com/example/dgbackend/domain/memberblock/controller/MemberBlockController.java
  src/main/java/com/example/dgbackend/domain/recommend/controller/RecommendController.java
  src/main/java/com/example/dgbackend/domain/report/controller/ReportController.java
  src/main/java/com/example/dgbackend/global/config/log/Interceptor.java
  src/main/java/com/example/dgbackend/global/config/log/LogAspect.java
  src/main/java/com/example/dgbackend/global/config/log/LogExecutionTime.java
  src/main/java/com/example/dgbackend/global/config/log/LogWebConfig.java
  src/main/java/com/example/dgbackend/global/exception/ApiException.java
  src/main/resources/log4j2.xml
Labels: :sparkles: Feature

#270 Fix: 프로필 사진 수정 로직 수정
  src/main/java/com/example/dgbackend/domain/member/controller/MemberRestController.java
  src/main/java/com/example/dgbackend/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/example/dgbackend/global/s3/S3Service.java
Labels: Fix

#271 [Main Merge] 로그 기능 구현, 프로필 이미지 오류 수정
  .gitignore
  build.gradle
  src/main/java/com/example/dgbackend/domain/member/controller/MemberRestController.java
  src/main/java/com/example/dgbackend/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/memberblock/controller/MemberBlockController.java
  src/main/java/com/example/dgbackend/domain/recommend/controller/RecommendController.java
  src/main/java/com/example/dgbackend/domain/report/controller/ReportController.java
  src/main/java/com/example/dgbackend/global/config/log/Interceptor.java
  src/main/java/com/example/dgbackend/global/config/log/LogAspect.java
  src/main/java/com/example/dgbackend/global/config/log/LogExecutionTime.java
  src/main/java/com/example/dgbackend/global/config/log/LogWebConfig.java
  src/main/java/com/example/dgbackend/global/exception/ApiException.java
  src/main/java/com/example/dgbackend/global/s3/S3Service.java
  src/main/resources/log4j2.xml
Labels: Main Merge
