Repository UMC5th-DrinkingGourmet/dg-BackEnd, pull requests merged in 2024-07, with the labels that each got.

#194 [Main Merge] JWT 예외,신고 / 애플로그인
  src/main/java/com/example/dgbackend/domain/member/Member.java
  src/main/java/com/example/dgbackend/global/jwt/controller/JwtController.java
  src/main/java/com/example/dgbackend/global/jwt/service/AuthService.java
Labels: Main Merge

#198 Fix: 댓글 차단 구현, 본인 차단 에러 수정
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/controller/CombinationCommentController.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/repository/CombinationCommentRepository.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/service/CombinationCommentQueryService.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/service/CombinationCommentQueryServiceImpl.java
  src/main/java/com/example/dgbackend/domain/memberblock/service/MemberBlockServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipecomment/controller/RecipeCommentController.java
  src/main/java/com/example/dgbackend/domain/recipecomment/repository/RecipeCommentRepository.java
  src/main/java/com/example/dgbackend/domain/recipecomment/service/RecipeCommentService.java
  src/main/java/com/example/dgbackend/domain/recipecomment/service/RecipeCommentServiceImpl.java
  src/main/java/com/example/dgbackend/global/common/response/code/status/ErrorStatus.java
Labels: Fix

#201 change: newMember 전달 방식 변경
  src/main/java/com/example/dgbackend/global/jwt/dto/AuthResponse.java
  src/main/java/com/example/dgbackend/global/jwt/service/AuthService.java
Labels: Change

#202 [Main Merge] newMember 전달 방식 변경
  src/main/java/com/example/dgbackend/global/jwt/dto/AuthResponse.java
  src/main/java/com/example/dgbackend/global/jwt/service/AuthService.java
Labels: Main Merge

#211 Fix: 좋아요한 게시글 목록 차단 적용
  src/main/java/com/example/dgbackend/domain/combination/repository/CombinationRepository.java
  src/main/java/com/example/dgbackend/domain/recipe/repository/RecipeRepository.java
Labels: Fix

#214 Feat: 레시피 리팩토링 및 멤버 검증 기능 구현
  src/main/java/com/example/dgbackend/domain/recipe/controller/RecipeController.java
  src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeRequest.java
  src/main/java/com/example/dgbackend/domain/recipe/service/RecipeService.java
  src/main/java/com/example/dgbackend/domain/recipe/service/RecipeServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipecomment/controller/RecipeCommentController.java
  src/main/java/com/example/dgbackend/domain/recipecomment/service/RecipeCommentService.java
  src/main/java/com/example/dgbackend/domain/recipecomment/service/RecipeCommentServiceImpl.java
  src/main/java/com/example/dgbackend/global/common/MemberValidator.java
  src/main/java/com/example/dgbackend/global/common/response/code/status/ErrorStatus.java
Labels: :sparkles: Feature

#224 220 [FEAT] 약관 기능 구현
  src/main/java/com/example/dgbackend/domain/term/Term.java
  src/main/java/com/example/dgbackend/domain/term/TermType.java
  src/main/java/com/example/dgbackend/domain/term/repository/TermRepository.java
  src/main/java/com/example/dgbackend/domain/termagree/TermAgree.java
  src/main/java/com/example/dgbackend/domain/termagree/controller/TermAgreeController.java
  src/main/java/com/example/dgbackend/domain/termagree/dto/TermRequestDTO.java
  src/main/java/com/example/dgbackend/domain/termagree/dto/TermResponseDTO.java
  src/main/java/com/example/dgbackend/domain/termagree/repository/TermAgreeRepository.java
  src/main/java/com/example/dgbackend/domain/termagree/service/TermAgreeCommandService.java
  src/main/java/com/example/dgbackend/domain/termagree/service/TermAgreeCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/termagree/service/TermAgreeQueryService.java
  src/main/java/com/example/dgbackend/domain/termagree/service/TermAgreeQueryServiceImpl.java
Labels: :sparkles: Feature

#225 Feat : 커뮤니티 글 삭제 시 연관관계 삭제 구현
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationCommandService.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/repository/CombinationCommentRepository.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/service/CombinationCommentCommandService.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/service/CombinationCommentCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/combinationimage/repository/CombinationImageRepository.java
  src/main/java/com/example/dgbackend/domain/combinationimage/service/CombinationImageCommandService.java
  src/main/java/com/example/dgbackend/domain/combinationimage/service/CombinationImageCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/combinationlike/repository/CombinationLikeRepository.java
  src/main/java/com/example/dgbackend/domain/combinationlike/service/CombinationLikeCommandService.java
  src/main/java/com/example/dgbackend/domain/combinationlike/service/CombinationLikeCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/hashtagoption/repository/HashTagOptionRepository.java
  src/main/java/com/example/dgbackend/domain/hashtagoption/service/HashTagOptionCommandService.java
  src/main/java/com/example/dgbackend/domain/hashtagoption/service/HashTagOptionCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipe/controller/RecipeController.java
  src/main/java/com/example/dgbackend/domain/recipe/service/RecipeService.java
  src/main/java/com/example/dgbackend/domain/recipe/service/RecipeServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipe_hashtag/RecipeHashTag.java
  src/main/java/com/example/dgbackend/domain/recipe_hashtag/repository/RecipeHashTagRepository.java
  src/main/java/com/example/dgbackend/domain/recipe_hashtag/service/RecipeHashTagService.java
  src/main/java/com/example/dgbackend/domain/recipe_hashtag/service/RecipeHashTagServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipecomment/controller/RecipeCommentController.java
  src/main/java/com/example/dgbackend/domain/recipecomment/repository/RecipeCommentRepository.java
  src/main/java/com/example/dgbackend/domain/recipecomment/service/RecipeCommentService.java
  src/main/java/com/example/dgbackend/domain/recipecomment/service/RecipeCommentServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipeimage/controller/RecipeImageController.java
  src/main/java/com/example/dgbackend/domain/recipeimage/repository/RecipeImageRepository.java
  src/main/java/com/example/dgbackend/domain/recipeimage/service/RecipeImageService.java
  src/main/java/com/example/dgbackend/domain/recipelike/controller/RecipeLikeController.java
  src/main/java/com/example/dgbackend/domain/recipelike/repository/RecipeLikeRepository.java
  src/main/java/com/example/dgbackend/domain/recipelike/service/RecipeLikeService.java
  src/main/java/com/example/dgbackend/domain/recipelike/service/RecipeLikeServiceImpl.java
Labels: :sparkles: Feature
