Repository UMC5th-DrinkingGourmet/dg-BackEnd, pull requests merged in 2024-01, with the labels that each got.

#6 Feat: 공통 응답 설정
  src/main/java/com/example/dgbackend/global/common/response/ApiResponse.java
  src/main/java/com/example/dgbackend/global/common/response/code/BaseCode.java
  src/main/java/com/example/dgbackend/global/common/response/code/BaseErrorCode.java
  src/main/java/com/example/dgbackend/global/common/response/code/ErrorReasonDto.java
  src/main/java/com/example/dgbackend/global/common/response/code/ReasonDto.java
  src/main/java/com/example/dgbackend/global/common/response/code/status/ErrorStatus.java
  src/main/java/com/example/dgbackend/global/common/response/code/status/SuccessStatus.java
Labels: :sparkles: Feature

#7 Docs: Recommend Entity 수정
  src/main/java/com/example/dgbackend/domain/recommend/Recommend.java
Labels: :memo: Docs

#11 Feat : 에러 핸들러 설정 완료
  src/main/java/com/example/dgbackend/global/common/response/ApiResponse.java
  src/main/java/com/example/dgbackend/global/exception/ApiException.java
  src/main/java/com/example/dgbackend/global/exception/ExceptionAdvice.java
Labels: :sparkles: Feature

#15 Docs : Member Entity limit 컬럼명 변경 및 FoodType 관련 Entity 삭제
  src/main/java/com/example/dgbackend/domain/foodtype/FoodType.java
  src/main/java/com/example/dgbackend/domain/member/Member.java
  src/main/java/com/example/dgbackend/domain/memberfoodtype/MemberFoodType.java
Labels: :memo: Docs

#32 Feat: 주류 추천 정보 입력 구현
  src/main/java/com/example/dgbackend/domain/member/Member.java
  src/main/java/com/example/dgbackend/domain/member/controller/MemberRestController.java
  src/main/java/com/example/dgbackend/domain/member/dto/MemberRequest.java
  src/main/java/com/example/dgbackend/domain/member/dto/MemberResponse.java
  src/main/java/com/example/dgbackend/domain/member/repository/MemberRepository.java
  src/main/java/com/example/dgbackend/domain/member/service/MemberCommandService.java
  src/main/java/com/example/dgbackend/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/member/service/MemberQueryService.java
  src/main/java/com/example/dgbackend/domain/member/service/MemberQueryServiceImpl.java
Labels: :sparkles: Feature

#22 feat: 오늘의 조합 홈 조회 API 구현
  src/main/java/com/example/dgbackend/domain/combination/controller/CombinationController.java
  src/main/java/com/example/dgbackend/domain/combination/domain/Combination.java
  src/main/java/com/example/dgbackend/domain/combination/dto/CombinationResponse.java
  src/main/java/com/example/dgbackend/domain/combination/repository/CombinationRepository.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryService.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/CombinationComment.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/controller/CombinationCommentController.java
  src/main/java/com/example/dgbackend/domain/combinationimage/CombinationImage.java
  src/main/java/com/example/dgbackend/domain/combinationlike/controller/CombinationLikeController.java
Labels: :sparkles: Feature

#24 feat: 오늘의 조합 상세 정보 조회 API
  src/main/java/com/example/dgbackend/domain/combination/Combination.java
  src/main/java/com/example/dgbackend/domain/combination/controller/CombinationController.java
  src/main/java/com/example/dgbackend/domain/combination/dto/CombinationResponse.java
  src/main/java/com/example/dgbackend/domain/combination/repository/CombinationRepository.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryService.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/CombinationComment.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/dto/CombinationCommentResponse.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/repository/CombinationCommentRepository.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/service/CombinationCommentQueryService.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/service/CombinationCommentQueryServiceImpl.java
  src/main/java/com/example/dgbackend/domain/combinationimage/CombinationImage.java
  src/main/java/com/example/dgbackend/domain/combinationlike/CombinationLike.java
  src/main/java/com/example/dgbackend/domain/hashtagoption/HashTagOption.java
  src/main/java/com/example/dgbackend/domain/member/dto/MemberResponse.java
Labels: :sparkles: Feature

#26 feat: 오늘의 조합 수정 정보 조회 API 구현
  src/main/java/com/example/dgbackend/domain/combination/controller/CombinationController.java
  src/main/java/com/example/dgbackend/domain/combination/domain/Combination.java
  src/main/java/com/example/dgbackend/domain/combination/dto/CombinationResponse.java
  src/main/java/com/example/dgbackend/domain/combination/repository/CombinationRepository.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryService.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/domain/CombinationComment.java
  src/main/java/com/example/dgbackend/domain/combinationlike/CombinationLike.java
  src/main/java/com/example/dgbackend/domain/hashtag/HashTag.java
  src/main/java/com/example/dgbackend/domain/hashtag/HashTagRepository.java
  src/main/java/com/example/dgbackend/domain/hashtagoption/HashTagOption.java
  src/main/java/com/example/dgbackend/domain/hashtagoption/repository/HashTagOptionRepository.java
  src/main/java/com/example/dgbackend/domain/member/domain/Member.java
  src/main/java/com/example/dgbackend/domain/member/repository/MemberRepository.java
  src/main/java/com/example/dgbackend/domain/memberdrinktype/MemberDrinkType.java
  src/main/java/com/example/dgbackend/domain/qna/QnA.java
  src/main/java/com/example/dgbackend/domain/recipe/Recipe.java
  src/main/java/com/example/dgbackend/domain/recipecomment/RecipeComment.java
  src/main/java/com/example/dgbackend/domain/recipelike/RecipeLike.java
  src/main/java/com/example/dgbackend/domain/recommend/Recommend.java
  src/main/java/com/example/dgbackend/domain/termagree/TermAgree.java
  src/main/java/com/example/dgbackend/global/common/response/code/status/ErrorStatus.java
Labels: :sparkles: Feature

#31 feat: 오늘의 조합 작성 API 구현
  src/main/java/com/example/dgbackend/domain/combination/controller/CombinationController.java
  src/main/java/com/example/dgbackend/domain/combination/domain/Combination.java
  src/main/java/com/example/dgbackend/domain/combination/dto/CombinationRequest.java
  src/main/java/com/example/dgbackend/domain/combination/dto/CombinationResponse.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationCommandService.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/combinationimage/domain/CombinationImage.java
  src/main/java/com/example/dgbackend/domain/combinationimage/repository/CombinationImageRepository.java
  src/main/java/com/example/dgbackend/domain/hashtag/HashTag.java
  src/main/java/com/example/dgbackend/domain/hashtag/repository/HashTagRepository.java
  src/main/java/com/example/dgbackend/domain/hashtag/service/HashTagCommandService.java
  src/main/java/com/example/dgbackend/domain/hashtag/service/HashTagCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/hashtagoption/HashTagOption.java
  src/main/java/com/example/dgbackend/domain/recommend/controller/RecommendController.java
Labels: :sparkles: Feature

#39 Feat: 오늘의 조합 삭제 API 구현
  src/main/java/com/example/dgbackend/domain/combination/Combination.java
  src/main/java/com/example/dgbackend/domain/combination/controller/CombinationController.java
  src/main/java/com/example/dgbackend/domain/combination/dto/CombinationResponse.java
  src/main/java/com/example/dgbackend/domain/combination/repository/CombinationRepository.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationCommandService.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryService.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/CombinationComment.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/dto/CombinationCommentResponse.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/repository/CombinationCommentRepository.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/service/CombinationCommentQueryService.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/service/CombinationCommentQueryServiceImpl.java
  src/main/java/com/example/dgbackend/domain/combinationimage/CombinationImage.java
  src/main/java/com/example/dgbackend/domain/combinationimage/repository/CombinationImageRepository.java
  src/main/java/com/example/dgbackend/domain/combinationimage/service/CombinationImageQueryService.java
  src/main/java/com/example/dgbackend/domain/combinationimage/service/CombinationImageQueryServiceImpl.java
  src/main/java/com/example/dgbackend/domain/combinationlike/repository/CombinationLikeRepository.java
  src/main/java/com/example/dgbackend/domain/combinationlike/service/CombinationLikeCommandService.java
  src/main/java/com/example/dgbackend/domain/combinationlike/service/CombinationLikeCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/hashtag/HashTag.java
  src/main/java/com/example/dgbackend/domain/hashtag/HashTagRepository.java
  src/main/java/com/example/dgbackend/domain/hashtag/service/HashTagCommandService.java
  src/main/java/com/example/dgbackend/domain/hashtag/service/HashTagCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/hashtagoption/HashTagOption.java
  src/main/java/com/example/dgbackend/domain/hashtagoption/repository/HashTagOptionRepository.java
  src/main/java/com/example/dgbackend/domain/hashtagoption/service/HashTagOptionCommandService.java
  src/main/java/com/example/dgbackend/domain/hashtagoption/service/HashTagOptionCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/member/Member.java
  src/main/java/com/example/dgbackend/domain/member/repository/MemberRepository.java
  src/main/java/com/example/dgbackend/domain/memberdrinktype/MemberDrinkType.java
  src/main/java/com/example/dgbackend/domain/qna/QnA.java
  src/main/java/com/example/dgbackend/domain/recipe/Recipe.java
  src/main/java/com/example/dgbackend/domain/recipecomment/RecipeComment.java
  src/main/java/com/example/dgbackend/domain/recipelike/RecipeLike.java
  src/main/java/com/example/dgbackend/domain/recommend/Recommend.java
  src/main/java/com/example/dgbackend/domain/recommend/dto/RecommendResponse.java
  src/main/java/com/example/dgbackend/domain/recommend/repository/RecommendRepository.java
  src/main/java/com/example/dgbackend/domain/recommend/service/RecommendQueryServiceImpl.java
  src/main/java/com/example/dgbackend/domain/termagree/TermAgree.java
  src/main/java/com/example/dgbackend/global/common/response/code/status/ErrorStatus.java
  src/main/java/com/example/dgbackend/global/s3/S3Service.java
Labels: :sparkles: Feature

#41 Feat: 오늘의 조합 수정 처리 API 구현
  src/main/java/com/example/dgbackend/domain/combination/Combination.java
  src/main/java/com/example/dgbackend/domain/combination/controller/CombinationController.java
  src/main/java/com/example/dgbackend/domain/combination/dto/CombinationRequest.java
  src/main/java/com/example/dgbackend/domain/combination/dto/CombinationResponse.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationCommandService.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryService.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/controller/CombinationCommentController.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/dto/CombinationCommentResponse.java
  src/main/java/com/example/dgbackend/domain/combinationimage/dto/CombinationImageResponse.java
  src/main/java/com/example/dgbackend/domain/combinationimage/repository/CombinationImageRepository.java
  src/main/java/com/example/dgbackend/domain/combinationimage/service/CombinationImageCommandService.java
  src/main/java/com/example/dgbackend/domain/combinationimage/service/CombinationImageCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/combinationlike/controller/CombinationLikeController.java
  src/main/java/com/example/dgbackend/domain/hashtag/HashTag.java
  src/main/java/com/example/dgbackend/domain/hashtag/repository/HashTagRepository.java
  src/main/java/com/example/dgbackend/domain/hashtag/service/HashTagCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/hashtag/service/HashTagQueryService.java
  src/main/java/com/example/dgbackend/domain/hashtag/service/HashTagQueryServiceImpl.java
  src/main/java/com/example/dgbackend/domain/hashtagoption/repository/HashTagOptionRepository.java
  src/main/java/com/example/dgbackend/domain/hashtagoption/service/HashTagOptionCommandService.java
  src/main/java/com/example/dgbackend/domain/hashtagoption/service/HashTagOptionCommandServiceImpl.java
Labels: :memo: Docs, :sparkles: Feature

#43 refactor: 오늘의 조합 작성 API 재구현
  src/main/java/com/example/dgbackend/domain/combination/controller/CombinationController.java
  src/main/java/com/example/dgbackend/domain/combination/dto/CombinationResponse.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationCommandService.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryService.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/CombinationComment.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/service/CombinationCommentQueryServiceImpl.java
  src/main/java/com/example/dgbackend/domain/combinationimage/CombinationImage.java
  src/main/java/com/example/dgbackend/domain/combinationimage/controller/CombinationImageController.java
  src/main/java/com/example/dgbackend/domain/combinationimage/repository/CombinationImageRepository.java
  src/main/java/com/example/dgbackend/domain/combinationimage/service/CombinationImageCommandService.java
  src/main/java/com/example/dgbackend/domain/combinationimage/service/CombinationImageCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/combinationimage/service/CombinationImageQueryServiceImpl.java
  src/main/java/com/example/dgbackend/domain/combinationlike/CombinationLike.java
  src/main/java/com/example/dgbackend/domain/hashtag/repository/HashTagRepository.java
  src/main/java/com/example/dgbackend/domain/hashtag/service/HashTagCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/hashtag/service/HashTagQueryServiceImpl.java
  src/main/java/com/example/dgbackend/domain/hashtagoption/HashTagOption.java
  src/main/java/com/example/dgbackend/domain/hashtagoption/repository/HashTagOptionRepository.java
  src/main/java/com/example/dgbackend/domain/hashtagoption/service/HashTagOptionCommandService.java
  src/main/java/com/example/dgbackend/domain/hashtagoption/service/HashTagOptionCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/member/Member.java
  src/main/java/com/example/dgbackend/domain/member/controller/MemberRestController.java
  src/main/java/com/example/dgbackend/domain/member/dto/MemberResponse.java
  src/main/java/com/example/dgbackend/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/member/service/MemberQueryServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recommend/Recommend.java
  src/main/java/com/example/dgbackend/domain/recommend/controller/RecommendController.java
  src/main/java/com/example/dgbackend/domain/recommend/service/RecommendQueryService.java
  src/main/java/com/example/dgbackend/domain/recommend/service/RecommendQueryServiceImpl.java
  src/main/java/com/example/dgbackend/domain/termagree/TermAgree.java
  src/main/java/com/example/dgbackend/global/common/response/code/status/ErrorStatus.java
Labels: :recycle: Refactor

#35 Feat : 레시피 기본 설정 및 API
  src/main/java/com/example/dgbackend/domain/member/Member.java
  src/main/java/com/example/dgbackend/domain/member/repository/MemberRepository.java
  src/main/java/com/example/dgbackend/domain/member/service/MemberService.java
  src/main/java/com/example/dgbackend/domain/recipe/Recipe.java
  src/main/java/com/example/dgbackend/domain/recipe/controller/RecipeController.java
  src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeParamVO.java
  src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeRequest.java
  src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeResponse.java
  src/main/java/com/example/dgbackend/domain/recipe/repository/RecipeRepository.java
  src/main/java/com/example/dgbackend/domain/recipe/service/RecipeService.java
  src/main/java/com/example/dgbackend/domain/recipe/service/RecipeServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipelike/repository/RecipeLikeRepository.java
  src/main/java/com/example/dgbackend/global/common/response/code/status/ErrorStatus.java
Labels: :sparkles: Feature

#48 FIX: 오늘의 조합 삭제 API 수정
  src/main/java/com/example/dgbackend/global/s3/S3Service.java
Labels: Fix

#52 Feat : 레시피 좋아요 API
  src/main/java/com/example/dgbackend/domain/recipelike/RecipeLike.java
  src/main/java/com/example/dgbackend/domain/recipelike/controller/RecipeLikeController.java
  src/main/java/com/example/dgbackend/domain/recipelike/dto/RecipeLikeRequest.java
  src/main/java/com/example/dgbackend/domain/recipelike/dto/RecipeLikeResponse.java
  src/main/java/com/example/dgbackend/domain/recipelike/dto/RecipeLikeVO.java
  src/main/java/com/example/dgbackend/domain/recipelike/service/RecipeLikeService.java
  src/main/java/com/example/dgbackend/domain/recipelike/service/RecipeLikeServiceImpl.java
Labels: :sparkles: Feature

#59 [FEAT] 오늘의 조합 댓글 조회 API 개발
  src/main/java/com/example/dgbackend/domain/combination/controller/CombinationController.java
  src/main/java/com/example/dgbackend/domain/combination/dto/CombinationResponse.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryService.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/CombinationComment.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/controller/CombinationCommentController.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/dto/CombinationCommentResponse.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/repository/CombinationCommentRepository.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/service/CombinationCommentQueryService.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/service/CombinationCommentQueryServiceImpl.java
  src/main/java/com/example/dgbackend/global/common/response/code/status/ErrorStatus.java
  src/main/java/com/example/dgbackend/global/validation/annotation/CheckPage.java
  src/main/java/com/example/dgbackend/global/validation/annotation/ExistCombination.java
  src/main/java/com/example/dgbackend/global/validation/validator/CombinationExistValidator.java
  src/main/java/com/example/dgbackend/global/validation/validator/PageCheckValidator.java
Labels: :recycle: Refactor, :sparkles: Feature

#65 fix: Merge Conflict 해결
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/dto/CombinationCommentResponse.java
  src/main/java/com/example/dgbackend/domain/member/Member.java
Labels: Fix

#71 Feat: 추천 삭제 API
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
  src/main/java/com/example/dgbackend/domain/member/Member.java
  src/main/java/com/example/dgbackend/domain/recommend/controller/RecommendController.java
  src/main/java/com/example/dgbackend/domain/recommend/service/RecommendQueryService.java
  src/main/java/com/example/dgbackend/domain/recommend/service/RecommendQueryServiceImpl.java
Labels: :sparkles: Feature

#72 Feat: 주류 추천 리스트 API
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recommend/controller/RecommendController.java
  src/main/java/com/example/dgbackend/domain/recommend/dto/RecommendResponse.java
  src/main/java/com/example/dgbackend/domain/recommend/repository/RecommendRepository.java
  src/main/java/com/example/dgbackend/domain/recommend/service/RecommendQueryService.java
  src/main/java/com/example/dgbackend/domain/recommend/service/RecommendQueryServiceImpl.java
Labels: :sparkles: Feature

#70 Docs : 레시피 Swagger 설정
  src/main/java/com/example/dgbackend/domain/recipe/controller/RecipeController.java
  src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeRequest.java
  src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeResponse.java
  src/main/java/com/example/dgbackend/domain/recipecomment/controller/RecipeCommentController.java
  src/main/java/com/example/dgbackend/domain/recipecomment/dto/RecipeCommentRequest.java
  src/main/java/com/example/dgbackend/domain/recipecomment/dto/RecipeCommentResponse.java
  src/main/java/com/example/dgbackend/domain/recipelike/controller/RecipeLikeController.java
  src/main/java/com/example/dgbackend/domain/recipelike/dto/RecipeLikeResponse.java
Labels: :memo: Docs

#74 Feat: 주간 베스트 조합 조회 API
  src/main/java/com/example/dgbackend/domain/combination/controller/CombinationController.java
  src/main/java/com/example/dgbackend/domain/combination/repository/CombinationRepository.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryService.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
Labels: :sparkles: Feature

#75 Feat: 오늘의 조합 댓글 삭제 API 구현
  src/main/java/com/example/dgbackend/domain/combinationcomment/CombinationComment.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/controller/CombinationCommentController.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/dto/CombinationCommentResponse.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/service/CombinationCommentCommandService.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/service/CombinationCommentCommandServiceImpl.java
Labels: :sparkles: Feature

#77 Feat: 오늘의 조합 좋아요 누르기 API
  src/main/java/com/example/dgbackend/domain/combination/Combination.java
  src/main/java/com/example/dgbackend/domain/combinationlike/CombinationLike.java
  src/main/java/com/example/dgbackend/domain/combinationlike/controller/CombinationLikeController.java
  src/main/java/com/example/dgbackend/domain/combinationlike/repository/CombinationLikeRepository.java
  src/main/java/com/example/dgbackend/domain/combinationlike/service/CombinationLikeQueryService.java
  src/main/java/com/example/dgbackend/domain/combinationlike/service/CombinationLikeQueryServiceImpl.java
Labels: :sparkles: Feature

#78 Feat: 소셜 로그인 (Kakao, Naver) API 개발
  build.gradle
  src/main/java/com/example/dgbackend/domain/enums/Role.java
  src/main/java/com/example/dgbackend/domain/member/Member.java
  src/main/java/com/example/dgbackend/domain/member/repository/MemberRepository.java
  src/main/java/com/example/dgbackend/global/common/response/code/status/ErrorStatus.java
  src/main/java/com/example/dgbackend/global/config/RedisConfig.java
  src/main/java/com/example/dgbackend/global/config/SwaggerConfig.java
  src/main/java/com/example/dgbackend/global/exception/ApiException.java
  src/main/java/com/example/dgbackend/global/exception/ExceptionAdvice.java
  src/main/java/com/example/dgbackend/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/dgbackend/global/jwt/JwtController.java
  src/main/java/com/example/dgbackend/global/jwt/JwtProvider.java
  src/main/java/com/example/dgbackend/global/security/SecurityConfig.java
  src/main/java/com/example/dgbackend/global/security/oauth2/controller/OAuth2Controller.java
  src/main/java/com/example/dgbackend/global/security/oauth2/dto/response/AuthResponse.java
  src/main/java/com/example/dgbackend/global/security/oauth2/handler/CustomLogoutHandler.java
  src/main/java/com/example/dgbackend/global/security/oauth2/handler/OAuth2AuthSuccessHandler.java
  src/main/java/com/example/dgbackend/global/security/oauth2/principal/CustomOAuth2User.java
  src/main/java/com/example/dgbackend/global/security/oauth2/service/AuthService.java
  src/main/java/com/example/dgbackend/global/security/oauth2/service/CustomOAuth2UserService.java
  src/main/java/com/example/dgbackend/global/security/oauth2/userInfo/AppleUserInfo.java
  src/main/java/com/example/dgbackend/global/security/oauth2/userInfo/KakaoUserInfo.java
  src/main/java/com/example/dgbackend/global/security/oauth2/userInfo/NaverUserInfo.java
  src/main/java/com/example/dgbackend/global/security/oauth2/userInfo/OAuth2UserInfo.java
  src/main/java/com/example/dgbackend/global/security/oauth2/userInfo/OAuth2UserInfoFactory.java
  src/main/java/com/example/dgbackend/global/util/CookieUtil.java
  src/main/java/com/example/dgbackend/global/util/RedisUtil.java
Labels: :sparkles: Feature

#81 FIX: Merge conflict resolve
  src/main/java/com/example/dgbackend/domain/combinationcomment/service/CombinationCommentCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/member/Member.java
  src/main/java/com/example/dgbackend/domain/recipe/controller/RecipeController.java
  src/main/java/com/example/dgbackend/domain/recipecomment/controller/RecipeCommentController.java
  src/main/java/com/example/dgbackend/domain/recipecomment/dto/RecipeCommentResponse.java
  src/main/java/com/example/dgbackend/domain/recipecomment/repository/RecipeCommentRepository.java
  src/main/java/com/example/dgbackend/domain/recipecomment/service/RecipeCommentServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipeimage/dto/RecipeImageRequest.java
  src/main/java/com/example/dgbackend/domain/recipeimage/repository/RecipeImageRepository.java
  src/main/java/com/example/dgbackend/domain/recipelike/RecipeLike.java
  src/main/java/com/example/dgbackend/domain/recipelike/controller/RecipeLikeController.java
  src/main/java/com/example/dgbackend/domain/recipelike/dto/RecipeLikeVO.java
  src/main/java/com/example/dgbackend/domain/recipelike/service/RecipeLikeServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recommend/controller/RecommendController.java
  src/main/java/com/example/dgbackend/domain/recommend/dto/RecommendRequest.java
  src/main/java/com/example/dgbackend/domain/recommend/dto/RecommendResponse.java
  src/main/java/com/example/dgbackend/domain/recommend/service/BASE64DecodedMultipartFile.java
  src/main/java/com/example/dgbackend/domain/recommend/service/RecommendCommandService.java
  src/main/java/com/example/dgbackend/domain/recommend/service/RecommendCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recommend/service/RecommendQueryService.java
  src/main/java/com/example/dgbackend/domain/recommend/service/RecommendQueryServiceImpl.java
Labels: Fix

#82 [Main Merge] 5회차
  src/main/java/com/example/dgbackend/domain/combinationcomment/service/CombinationCommentCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipe/controller/RecipeController.java
  src/main/java/com/example/dgbackend/domain/recipecomment/controller/RecipeCommentController.java
  src/main/java/com/example/dgbackend/domain/recipecomment/dto/RecipeCommentResponse.java
  src/main/java/com/example/dgbackend/domain/recipecomment/repository/RecipeCommentRepository.java
  src/main/java/com/example/dgbackend/domain/recipecomment/service/RecipeCommentServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipeimage/dto/RecipeImageRequest.java
  src/main/java/com/example/dgbackend/domain/recipeimage/repository/RecipeImageRepository.java
  src/main/java/com/example/dgbackend/domain/recipelike/RecipeLike.java
  src/main/java/com/example/dgbackend/domain/recipelike/controller/RecipeLikeController.java
  src/main/java/com/example/dgbackend/domain/recipelike/dto/RecipeLikeVO.java
  src/main/java/com/example/dgbackend/domain/recipelike/service/RecipeLikeServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recommend/controller/RecommendController.java
  src/main/java/com/example/dgbackend/domain/recommend/dto/RecommendRequest.java
  src/main/java/com/example/dgbackend/domain/recommend/dto/RecommendResponse.java
  src/main/java/com/example/dgbackend/domain/recommend/service/BASE64DecodedMultipartFile.java
  src/main/java/com/example/dgbackend/domain/recommend/service/RecommendCommandService.java
  src/main/java/com/example/dgbackend/domain/recommend/service/RecommendCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recommend/service/RecommendQueryService.java
  src/main/java/com/example/dgbackend/domain/recommend/service/RecommendQueryServiceImpl.java
Labels: Main Merge
