Repository UMC5th-DrinkingGourmet/dg-BackEnd, pull requests merged in 2024-08, with the labels that each got.

#228 Feat: 해시태그를 통한 검색 기능 추가
  src/main/java/com/example/dgbackend/domain/combination/repository/CombinationRepository.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipe/repository/RecipeRepository.java
  src/main/java/com/example/dgbackend/domain/recipe/service/RecipeServiceImpl.java
Labels: :sparkles: Feature

#230 Feat: 탈퇴하기 구현
  src/main/java/com/example/dgbackend/domain/cancellation/Cancellation.java
  src/main/java/com/example/dgbackend/domain/cancellation/repository/CancellationRepository.java
  src/main/java/com/example/dgbackend/domain/cancellation/service/CancellationCommandService.java
  src/main/java/com/example/dgbackend/domain/cancellation/service/CancellationCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/cancellation/service/CancellationSchedular.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationCommandService.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/CombinationComment.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/repository/CombinationCommentRepository.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/service/CombinationCommentCommandService.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/service/CombinationCommentCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/combinationlike/repository/CombinationLikeRepository.java
  src/main/java/com/example/dgbackend/domain/combinationlike/service/CombinationLikeCommandService.java
  src/main/java/com/example/dgbackend/domain/combinationlike/service/CombinationLikeCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/enums/Gender.java
  src/main/java/com/example/dgbackend/domain/member/controller/MemberRestController.java
  src/main/java/com/example/dgbackend/domain/member/repository/MemberRepository.java
  src/main/java/com/example/dgbackend/domain/member/service/MemberCommandService.java
  src/main/java/com/example/dgbackend/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/memberblock/repository/MemberBlockRepository.java
  src/main/java/com/example/dgbackend/domain/memberblock/service/MemberBlockService.java
  src/main/java/com/example/dgbackend/domain/memberblock/service/MemberBlockServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipe/repository/RecipeRepository.java
  src/main/java/com/example/dgbackend/domain/recipe/service/RecipeService.java
  src/main/java/com/example/dgbackend/domain/recipe/service/RecipeServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipecomment/RecipeComment.java
  src/main/java/com/example/dgbackend/domain/recipecomment/repository/RecipeCommentRepository.java
  src/main/java/com/example/dgbackend/domain/recipecomment/service/RecipeCommentService.java
  src/main/java/com/example/dgbackend/domain/recipecomment/service/RecipeCommentServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipelike/repository/RecipeLikeRepository.java
  src/main/java/com/example/dgbackend/domain/recipelike/service/RecipeLikeService.java
  src/main/java/com/example/dgbackend/domain/recipelike/service/RecipeLikeServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recommend/Recommend.java
  src/main/java/com/example/dgbackend/domain/recommend/repository/RecommendRepository.java
  src/main/java/com/example/dgbackend/domain/recommend/service/RecommendCommandService.java
  src/main/java/com/example/dgbackend/domain/recommend/service/RecommendCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/termagree/repository/TermAgreeRepository.java
  src/main/java/com/example/dgbackend/domain/termagree/service/TermAgreeCommandService.java
  src/main/java/com/example/dgbackend/domain/termagree/service/TermAgreeCommandServiceImpl.java
  src/main/java/com/example/dgbackend/global/common/response/code/status/ErrorStatus.java
  src/main/java/com/example/dgbackend/global/jwt/service/AuthService.java
Labels: :sparkles: Feature

#233 Fix/conflict
  src/main/java/com/example/dgbackend/domain/cancellation/Cancellation.java
  src/main/java/com/example/dgbackend/domain/cancellation/repository/CancellationRepository.java
  src/main/java/com/example/dgbackend/domain/cancellation/service/CancellationCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/cancellation/service/CancellationSchedular.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/CombinationComment.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/repository/CombinationCommentRepository.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/service/CombinationCommentCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/combinationlike/service/CombinationLikeCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/member/controller/MemberRestController.java
  src/main/java/com/example/dgbackend/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/memberblock/service/MemberBlockServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipe/repository/RecipeRepository.java
  src/main/java/com/example/dgbackend/domain/recipe/service/RecipeServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipecomment/RecipeComment.java
  src/main/java/com/example/dgbackend/domain/recipecomment/repository/RecipeCommentRepository.java
  src/main/java/com/example/dgbackend/domain/recipecomment/service/RecipeCommentServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipelike/RecipeLike.java
  src/main/java/com/example/dgbackend/domain/recipelike/repository/RecipeLikeRepository.java
  src/main/java/com/example/dgbackend/domain/recipelike/service/RecipeLikeService.java
  src/main/java/com/example/dgbackend/domain/recommend/Recommend.java
  src/main/java/com/example/dgbackend/domain/recommend/repository/RecommendRepository.java
  src/main/java/com/example/dgbackend/domain/recommend/service/RecommendCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/termagree/TermAgree.java
  src/main/java/com/example/dgbackend/domain/termagree/service/TermAgreeCommandServiceImpl.java
  src/main/java/com/example/dgbackend/global/common/response/code/status/ErrorStatus.java
  src/main/java/com/example/dgbackend/global/jwt/service/AuthService.java
Labels: Fix

#235 [fix] 추천 hard delete
  src/main/java/com/example/dgbackend/domain/cancellation/service/CancellationSchedular.java
  src/main/java/com/example/dgbackend/domain/combination/repository/CombinationRepository.java
  src/main/java/com/example/dgbackend/domain/recipe/repository/RecipeRepository.java
  src/main/java/com/example/dgbackend/domain/recipe/service/RecipeServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recommend/Recommend.java
  src/main/java/com/example/dgbackend/domain/recommend/repository/RecommendRepository.java
  src/main/java/com/example/dgbackend/domain/recommend/service/RecommendCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/report/repository/ReportRepository.java
  src/main/java/com/example/dgbackend/domain/report/service/ReportService.java
  src/main/java/com/example/dgbackend/domain/report/service/ReportServiceImpl.java
Labels: :sparkles: Feature

#236 [Main Merge] 추천 Hard Delete
  src/main/java/com/example/dgbackend/domain/cancellation/service/CancellationSchedular.java
  src/main/java/com/example/dgbackend/domain/combination/repository/CombinationRepository.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/repository/CombinationCommentRepository.java
  src/main/java/com/example/dgbackend/domain/member/controller/MemberRestController.java
  src/main/java/com/example/dgbackend/domain/recipe/repository/RecipeRepository.java
  src/main/java/com/example/dgbackend/domain/recipe/service/RecipeServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recommend/Recommend.java
  src/main/java/com/example/dgbackend/domain/recommend/repository/RecommendRepository.java
  src/main/java/com/example/dgbackend/domain/recommend/service/RecommendCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/report/repository/ReportRepository.java
  src/main/java/com/example/dgbackend/domain/report/service/ReportService.java
  src/main/java/com/example/dgbackend/domain/report/service/ReportServiceImpl.java
  src/main/java/com/example/dgbackend/global/jwt/service/AuthService.java
Labels: Main Merge

#240 [CHANGE] 약관 정책 수정
  src/main/java/com/example/dgbackend/domain/term/TermType.java
Labels: Change

#242 Refactor: 오늘의 조합 상세조회 Response 수정
  src/main/java/com/example/dgbackend/domain/combination/dto/CombinationResponse.java
Labels: :recycle: Refactor

#245 [fix] Combination 추가 오류 수정
  src/main/java/com/example/dgbackend/domain/combination/dto/CombinationRequest.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationCommandServiceImpl.java
Labels: Fix

#247 [CHANGE] 레시피 이미지 업로드 방식 수정
  src/main/java/com/example/dgbackend/domain/recipe/Recipe.java
  src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeRequest.java
  src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeResponse.java
  src/main/java/com/example/dgbackend/domain/recipe/service/RecipeServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipeimage/RecipeImage.java
  src/main/java/com/example/dgbackend/domain/recipeimage/controller/RecipeImageController.java
  src/main/java/com/example/dgbackend/domain/recipeimage/dto/RecipeImageResponse.java
  src/main/java/com/example/dgbackend/domain/recipeimage/repository/RecipeImageRepository.java
  src/main/java/com/example/dgbackend/domain/recipeimage/service/RecipeImageService.java
Labels: Change
