Repository UMC5th-DrinkingGourmet/dg-BackEnd, pull requests merged in 2024-02, with the labels that each got.

#93 Feat: MyPage 관련 API 모음
  src/main/java/com/example/dgbackend/domain/combination/controller/CombinationController.java
  src/main/java/com/example/dgbackend/domain/combination/dto/CombinationResponse.java
  src/main/java/com/example/dgbackend/domain/combination/repository/CombinationRepository.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationCommandService.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryService.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/repository/CombinationCommentRepository.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/service/CombinationCommentCommandService.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/service/CombinationCommentCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/combinationlike/repository/CombinationLikeRepository.java
  src/main/java/com/example/dgbackend/domain/combinationlike/service/CombinationLikeCommandService.java
  src/main/java/com/example/dgbackend/domain/combinationlike/service/CombinationLikeCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/member/Member.java
  src/main/java/com/example/dgbackend/domain/member/controller/MemberRestController.java
  src/main/java/com/example/dgbackend/domain/member/dto/MemberRequest.java
  src/main/java/com/example/dgbackend/domain/member/dto/MemberResponse.java
  src/main/java/com/example/dgbackend/domain/member/service/MemberCommandService.java
  src/main/java/com/example/dgbackend/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipe/Recipe.java
  src/main/java/com/example/dgbackend/domain/recipe/controller/RecipeController.java
  src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeResponse.java
  src/main/java/com/example/dgbackend/domain/recipe/repository/RecipeRepository.java
  src/main/java/com/example/dgbackend/domain/recipe/service/RecipeService.java
  src/main/java/com/example/dgbackend/domain/recipe/service/RecipeServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipecomment/repository/RecipeCommentRepository.java
  src/main/java/com/example/dgbackend/domain/recipecomment/service/RecipeCommentService.java
  src/main/java/com/example/dgbackend/domain/recipecomment/service/RecipeCommentServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipelike/repository/RecipeLikeRepository.java
  src/main/java/com/example/dgbackend/domain/recipelike/service/RecipeLikeService.java
  src/main/java/com/example/dgbackend/domain/recipelike/service/RecipeLikeServiceImpl.java
  src/main/java/com/example/dgbackend/global/s3/S3Service.java
Labels: :sparkles: Feature

#96 Feat : 레시피 Count 변경 기능 추가
  src/main/java/com/example/dgbackend/domain/recipe/Recipe.java
  src/main/java/com/example/dgbackend/domain/recipecomment/RecipeComment.java
  src/main/java/com/example/dgbackend/domain/recipecomment/service/RecipeCommentServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipelike/RecipeLike.java
  src/main/java/com/example/dgbackend/domain/recipelike/service/RecipeLikeServiceImpl.java
  src/main/java/com/example/dgbackend/global/common/response/code/status/ErrorStatus.java
Labels: :sparkles: Feature

#94 Feat : 레시피 페이징
  src/main/java/com/example/dgbackend/domain/recipe/controller/RecipeController.java
  src/main/java/com/example/dgbackend/domain/recipe/repository/RecipeRepository.java
  src/main/java/com/example/dgbackend/domain/recipe/service/RecipeService.java
  src/main/java/com/example/dgbackend/domain/recipe/service/RecipeServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipecomment/controller/RecipeCommentController.java
  src/main/java/com/example/dgbackend/domain/recipecomment/repository/RecipeCommentRepository.java
  src/main/java/com/example/dgbackend/domain/recipecomment/service/RecipeCommentService.java
  src/main/java/com/example/dgbackend/domain/recipecomment/service/RecipeCommentServiceImpl.java
Labels: :sparkles: Feature

#100 [Main Merge] 10회차
  src/main/java/com/example/dgbackend/domain/recipe/controller/RecipeController.java
Labels: Main Merge

#103 Fix: Recommend 도메인 Member어노테이션 추가 및 Soft Delete구현
  src/main/java/com/example/dgbackend/domain/recommend/Recommend.java
  src/main/java/com/example/dgbackend/domain/recommend/controller/RecommendController.java
  src/main/java/com/example/dgbackend/domain/recommend/dto/RecommendResponse.java
  src/main/java/com/example/dgbackend/domain/recommend/service/RecommendCommandService.java
  src/main/java/com/example/dgbackend/domain/recommend/service/RecommendCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recommend/service/RecommendQueryService.java
  src/main/java/com/example/dgbackend/domain/recommend/service/RecommendQueryServiceImpl.java
  src/main/java/com/example/dgbackend/global/common/response/code/status/ErrorStatus.java
Labels: :recycle: Refactor, Fix

#111 fix: 소셜 로그인 처리 후 Refresh Toekn 전달 방법 수정
  src/main/java/com/example/dgbackend/global/jwt/JwtProvider.java
  src/main/java/com/example/dgbackend/global/jwt/controller/JwtController.java
  src/main/java/com/example/dgbackend/global/jwt/handler/CustomLogoutHandler.java
  src/main/java/com/example/dgbackend/global/jwt/service/AuthService.java
Labels: Fix

#119 fix: 댓글 조회 API 수정 및 CommentResult 수정
  src/main/java/com/example/dgbackend/domain/combination/Combination.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/CombinationComment.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/dto/CombinationCommentResponse.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/repository/CombinationCommentRepository.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/service/CombinationCommentQueryServiceImpl.java
  src/main/java/com/example/dgbackend/domain/member/service/MemberQueryService.java
  src/main/java/com/example/dgbackend/domain/member/service/MemberQueryServiceImpl.java
  src/main/java/com/example/dgbackend/global/jwt/dto/AuthResponse.java
  src/main/java/com/example/dgbackend/global/jwt/service/AuthService.java
Labels: Fix

#110 FEAT : 메인 최상단 주간 베스트 조회 API & 메인 로테이션 오늘의 조합 조회 API & 메인 로테이션 레시피북 조회 API
  src/main/java/com/example/dgbackend/AppInitialization.java
  src/main/java/com/example/dgbackend/DgBackEndApplication.java
  src/main/java/com/example/dgbackend/domain/combination/controller/CombinationController.java
  src/main/java/com/example/dgbackend/domain/combination/dto/CombinationResponse.java
  src/main/java/com/example/dgbackend/domain/combination/repository/CombinationRepository.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryService.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationScheduler.java
  src/main/java/com/example/dgbackend/domain/combinationimage/repository/CombinationImageRepository.java
  src/main/java/com/example/dgbackend/domain/recipe/controller/RecipeController.java
  src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeResponse.java
  src/main/java/com/example/dgbackend/domain/recipe/repository/RecipeRepository.java
  src/main/java/com/example/dgbackend/domain/recipe/service/RecipeScheduler.java
  src/main/java/com/example/dgbackend/domain/recipeimage/repository/RecipeImageRepository.java
Labels: :sparkles: Feature

#115 Fix: 오늘의 조합 좋아요 API 멤버 어노테이션 적용
  src/main/java/com/example/dgbackend/domain/combinationlike/controller/CombinationLikeController.java
  src/main/java/com/example/dgbackend/domain/combinationlike/service/CombinationLikeQueryService.java
  src/main/java/com/example/dgbackend/domain/combinationlike/service/CombinationLikeQueryServiceImpl.java
Labels: Change

#120 [FEAT] 레시피북 Response 변경
  src/main/java/com/example/dgbackend/domain/recipe/controller/RecipeController.java
  src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeResponse.java
  src/main/java/com/example/dgbackend/domain/recipe/service/RecipeService.java
  src/main/java/com/example/dgbackend/domain/recipe/service/RecipeServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipeimage/dto/RecipeImageResponse.java
  src/main/java/com/example/dgbackend/domain/recipeimage/service/RecipeImageService.java
Labels: :recycle: Refactor, :sparkles: Feature

#121 [Main Merge] 12회차
  README.md
  src/main/java/com/example/dgbackend/AppInitialization.java
  src/main/java/com/example/dgbackend/DgBackEndApplication.java
  src/main/java/com/example/dgbackend/domain/combination/Combination.java
  src/main/java/com/example/dgbackend/domain/combination/controller/CombinationController.java
  src/main/java/com/example/dgbackend/domain/combination/dto/CombinationResponse.java
  src/main/java/com/example/dgbackend/domain/combination/repository/CombinationRepository.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryService.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationScheduler.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/CombinationComment.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/dto/CombinationCommentResponse.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/repository/CombinationCommentRepository.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/service/CombinationCommentQueryServiceImpl.java
  src/main/java/com/example/dgbackend/domain/combinationimage/repository/CombinationImageRepository.java
  src/main/java/com/example/dgbackend/domain/combinationlike/controller/CombinationLikeController.java
  src/main/java/com/example/dgbackend/domain/combinationlike/service/CombinationLikeQueryService.java
  src/main/java/com/example/dgbackend/domain/combinationlike/service/CombinationLikeQueryServiceImpl.java
  src/main/java/com/example/dgbackend/domain/member/service/MemberQueryService.java
  src/main/java/com/example/dgbackend/domain/member/service/MemberQueryServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipe/controller/RecipeController.java
  src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeResponse.java
  src/main/java/com/example/dgbackend/domain/recipe/repository/RecipeRepository.java
  src/main/java/com/example/dgbackend/domain/recipe/service/RecipeScheduler.java
  src/main/java/com/example/dgbackend/domain/recipe/service/RecipeService.java
  src/main/java/com/example/dgbackend/domain/recipe/service/RecipeServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipeimage/dto/RecipeImageResponse.java
  src/main/java/com/example/dgbackend/domain/recipeimage/repository/RecipeImageRepository.java
  src/main/java/com/example/dgbackend/domain/recipeimage/service/RecipeImageService.java
  src/main/java/com/example/dgbackend/global/jwt/dto/AuthResponse.java
  src/main/java/com/example/dgbackend/global/jwt/service/AuthService.java
Labels: Main Merge

#123 fix : memberName -> memberNickname 으로 변경
  src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeResponse.java
Labels: :recycle: Refactor

#124 [Main Merge] 14회차
  src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeResponse.java
Labels: Main Merge

#125 [Main Merge] 15회차
  src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeResponse.java
Labels: Main Merge

#126 Refactor : List Default값 추가
  src/main/java/com/example/dgbackend/domain/recipe/Recipe.java
Labels: Fix

#128 fix : MemberObject 추가
  src/main/java/com/example/dgbackend/domain/recipecomment/controller/RecipeCommentController.java
  src/main/java/com/example/dgbackend/domain/recipelike/controller/RecipeLikeController.java
Labels: Fix

#129 Feature : 레시피북 해시태그 추가
  src/main/java/com/example/dgbackend/domain/hashtag/service/HashTagCommandService.java
  src/main/java/com/example/dgbackend/domain/hashtag/service/HashTagCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipe/Recipe.java
  src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeRequest.java
  src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeResponse.java
  src/main/java/com/example/dgbackend/domain/recipe/service/RecipeServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipe_hashtag/RecipeHashTag.java
  src/main/java/com/example/dgbackend/domain/recipe_hashtag/dto/RecipeHashTagResponse.java
  src/main/java/com/example/dgbackend/domain/recipe_hashtag/repository/RecipeHashTagRepository.java
  src/main/java/com/example/dgbackend/domain/recipe_hashtag/service/RecipeHashTagService.java
  src/main/java/com/example/dgbackend/domain/recipe_hashtag/service/RecipeHashTagServiceImpl.java
Labels: :sparkles: Feature

#131 Fix: 주류 추천 ResponseDTO 변경
  src/main/java/com/example/dgbackend/domain/recommend/dto/RecommendResponse.java
  src/main/java/com/example/dgbackend/domain/recommend/service/RecommendCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recommend/service/RecommendQueryService.java
  src/main/java/com/example/dgbackend/domain/recommend/service/RecommendQueryServiceImpl.java
Labels: Fix

#132 [Main Merge] 16회차
  src/main/java/com/example/dgbackend/domain/hashtag/service/HashTagCommandService.java
  src/main/java/com/example/dgbackend/domain/hashtag/service/HashTagCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipe/Recipe.java
  src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeRequest.java
  src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeResponse.java
  src/main/java/com/example/dgbackend/domain/recipe/service/RecipeServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipe_hashtag/RecipeHashTag.java
  src/main/java/com/example/dgbackend/domain/recipe_hashtag/dto/RecipeHashTagResponse.java
  src/main/java/com/example/dgbackend/domain/recipe_hashtag/repository/RecipeHashTagRepository.java
  src/main/java/com/example/dgbackend/domain/recipe_hashtag/service/RecipeHashTagService.java
  src/main/java/com/example/dgbackend/domain/recipe_hashtag/service/RecipeHashTagServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipecomment/controller/RecipeCommentController.java
  src/main/java/com/example/dgbackend/domain/recipelike/controller/RecipeLikeController.java
  src/main/java/com/example/dgbackend/domain/recommend/dto/RecommendResponse.java
  src/main/java/com/example/dgbackend/domain/recommend/service/RecommendCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recommend/service/RecommendQueryService.java
  src/main/java/com/example/dgbackend/domain/recommend/service/RecommendQueryServiceImpl.java
Labels: Main Merge

#133 FEAT : 메인 새로 출시된 주류 조회 API, 새로 출시된 주류 상세 조회 API, 새로 출시된 주류 리스트 조회 API, 새로 출시된 주류 타입별 조회 API
  src/main/java/com/example/dgbackend/domain/combination/controller/CombinationController.java
  src/main/java/com/example/dgbackend/domain/combination/repository/CombinationRepository.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryService.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationScheduler.java
  src/main/java/com/example/dgbackend/domain/drinklist/DrinkList.java
  src/main/java/com/example/dgbackend/domain/drinklist/controller/DrinkListController.java
  src/main/java/com/example/dgbackend/domain/drinklist/dto/DrinkListResponse.java
  src/main/java/com/example/dgbackend/domain/drinklist/repository/DrinkListRepository.java
  src/main/java/com/example/dgbackend/domain/drinklist/service/DrinkListQueryService.java
  src/main/java/com/example/dgbackend/domain/drinklist/service/DrinkListQueryServiceImpl.java
  src/main/java/com/example/dgbackend/domain/enums/DrinkType.java
  src/main/java/com/example/dgbackend/domain/member/Member.java
  src/main/java/com/example/dgbackend/domain/recipe/controller/RecipeController.java
  src/main/java/com/example/dgbackend/domain/recipe/repository/RecipeRepository.java
  src/main/java/com/example/dgbackend/domain/recipe/service/RecipeScheduler.java
  src/main/java/com/example/dgbackend/domain/recipe/service/RecipeServiceImpl.java
  src/main/java/com/example/dgbackend/global/common/response/code/status/ErrorStatus.java
Labels: :sparkles: Feature

#135 FIX: 오늘의 조합 홈 페이지, 상세보기, 댓글 작성 DTO 수정
  src/main/java/com/example/dgbackend/domain/combinationcomment/dto/CombinationCommentResponse.java
  src/main/java/com/example/dgbackend/domain/member/dto/MemberResponse.java
Labels: Fix

#139 [Main Merge] 18회차
  src/main/java/com/example/dgbackend/domain/recipe/Recipe.java
  src/main/java/com/example/dgbackend/domain/recipe/controller/RecipeController.java
  src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeRequest.java
  src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeResponse.java
  src/main/java/com/example/dgbackend/domain/recipe/repository/RecipeRepository.java
  src/main/java/com/example/dgbackend/domain/recipe/service/RecipeService.java
  src/main/java/com/example/dgbackend/domain/recipe/service/RecipeServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipecomment/controller/RecipeCommentController.java
  src/main/java/com/example/dgbackend/domain/recipecomment/dto/RecipeCommentResponse.java
  src/main/java/com/example/dgbackend/domain/recipecomment/repository/RecipeCommentRepository.java
  src/main/java/com/example/dgbackend/domain/recipecomment/service/RecipeCommentService.java
  src/main/java/com/example/dgbackend/domain/recipecomment/service/RecipeCommentServiceImpl.java
Labels: Main Merge

#141 Refactor : 레시피북 프론트 요청
  src/main/java/com/example/dgbackend/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipe/controller/RecipeController.java
  src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeResponse.java
  src/main/java/com/example/dgbackend/domain/recipe/service/RecipeService.java
  src/main/java/com/example/dgbackend/domain/recipe/service/RecipeServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipecomment/service/RecipeCommentServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipelike/controller/RecipeLikeController.java
  src/main/java/com/example/dgbackend/domain/recipelike/service/RecipeLikeService.java
  src/main/java/com/example/dgbackend/domain/recipelike/service/RecipeLikeServiceImpl.java
Labels: :recycle: Refactor

#142 Fix: Docker 컨테이너 시간 설정
  .github/workflows/docker-deploy.yml
Labels: Fix

#143 [Main Merge] 19회차
  .github/workflows/docker-deploy.yml
  src/main/java/com/example/dgbackend/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipe/controller/RecipeController.java
  src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeResponse.java
  src/main/java/com/example/dgbackend/domain/recipe/service/RecipeService.java
  src/main/java/com/example/dgbackend/domain/recipe/service/RecipeServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipecomment/service/RecipeCommentServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipelike/controller/RecipeLikeController.java
  src/main/java/com/example/dgbackend/domain/recipelike/service/RecipeLikeService.java
  src/main/java/com/example/dgbackend/domain/recipelike/service/RecipeLikeServiceImpl.java
Labels: Main Merge

#144 Fix: 오늘의 조합 좋아요 여부 로직 수정
  src/main/java/com/example/dgbackend/domain/combinationlike/repository/CombinationLikeRepository.java
  src/main/java/com/example/dgbackend/domain/combinationlike/service/CombinationLikeQueryServiceImpl.java
Labels: Fix

#146 Fix: 이미지 생성 프롬프트 수정
  src/main/java/com/example/dgbackend/domain/recommend/service/RecommendCommandServiceImpl.java
Labels: Fix

#147 Fix: 오늘의 조합 API URL 및 댓글 DTO 수정
  src/main/java/com/example/dgbackend/domain/combination/controller/CombinationController.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/dto/CombinationCommentResponse.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/repository/CombinationCommentRepository.java
  src/main/java/com/example/dgbackend/domain/combinationcomment/service/CombinationCommentQueryServiceImpl.java
  src/main/java/com/example/dgbackend/global/config/SecurityConfig.java
Labels: Fix

#150 Refactor : 레시피 / 레시피 댓글에 유저 정보 추가
  src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeResponse.java
  src/main/java/com/example/dgbackend/domain/recipecomment/dto/RecipeCommentResponse.java
Labels: :recycle: Refactor

#152 [FIX]: CommentResult memberId 추가
  src/main/java/com/example/dgbackend/domain/combinationcomment/dto/CombinationCommentResponse.java
Labels: Fix

#154 Fix: 검색 시 State True 게시글만 조회
  src/main/java/com/example/dgbackend/domain/combination/repository/CombinationRepository.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipe/repository/RecipeRepository.java
  src/main/java/com/example/dgbackend/domain/recipe/service/RecipeServiceImpl.java
Labels: Fix

#155 [Main Merge] 23회차
  src/main/java/com/example/dgbackend/domain/combination/repository/CombinationRepository.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipe/repository/RecipeRepository.java
  src/main/java/com/example/dgbackend/domain/recipe/service/RecipeServiceImpl.java
Labels: Main Merge

#157 refactor: 좋아요 삭제 여부 반영
  src/main/java/com/example/dgbackend/domain/combination/repository/CombinationRepository.java
  src/main/java/com/example/dgbackend/domain/recipe/repository/RecipeRepository.java
Labels: :recycle: Refactor

#160 Fix: 오늘의 조합/레시피 홈 조회시 생성일 순으로 내림차순
  src/main/java/com/example/dgbackend/domain/combination/repository/CombinationRepository.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipe/repository/RecipeRepository.java
  src/main/java/com/example/dgbackend/domain/recipe/service/RecipeServiceImpl.java
Labels: Change

#161 [Main Merge] 25회차
  src/main/java/com/example/dgbackend/domain/combination/repository/CombinationRepository.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipe/repository/RecipeRepository.java
  src/main/java/com/example/dgbackend/domain/recipe/service/RecipeServiceImpl.java
Labels: Main Merge

#164 Fix: 주류 추천 및 내가 작성한 글 조회시 생성일 순으로 내림차순
  src/main/java/com/example/dgbackend/domain/combination/repository/CombinationRepository.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipe/repository/RecipeRepository.java
  src/main/java/com/example/dgbackend/domain/recipe/service/RecipeServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recommend/repository/RecommendRepository.java
  src/main/java/com/example/dgbackend/domain/recommend/service/RecommendQueryServiceImpl.java
Labels: Change

#165 [Main Merge] 27회차
  src/main/java/com/example/dgbackend/domain/combination/repository/CombinationRepository.java
  src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recipe/repository/RecipeRepository.java
  src/main/java/com/example/dgbackend/domain/recipe/service/RecipeServiceImpl.java
  src/main/java/com/example/dgbackend/domain/recommend/repository/RecommendRepository.java
  src/main/java/com/example/dgbackend/domain/recommend/service/RecommendQueryServiceImpl.java
Labels: Main Merge
